apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: db-critical
value: 1000000000
globalDefault: false
description: "High priority for critical data services (PostgreSQL/Redis/RabbitMQ)."


