{{- if .Values.envSecrets }}
# Optional Secret - only created if values are provided
{{- $secretName := .Values.envSecrets | first | .secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "app.fullname" . }}
type: Opaque
data:
  {{- range .Values.envSecrets }}
  {{ .secretKey }}: {{ .value | b64enc | quote }}
  {{- end }}
{{- end }}
